### PR TITLE
Update meshlight_add.py

### PR DESCRIPTION
**Pull request by riveter1**
- made grid bigger
- translated and rotated grid so it is off the origin and grid normals are facing downward
- reversed mix inputs accordingly

### CODE REVIEW

**Comment by venomgfx** [comment]
Hi,

Thanks for fixing the rotation, totally went over my head. I also think the grid bigger makes more sense. The only thing I'd rather not have is the location offset. Since objects get added under the 3D Cursor, it's always predictable where new objects are going to appear. If we offset them on creation it's we're breaking the expectations and it's not very good UX.

Besides that, looks good!

**Comment by riveter1** [comment]
Pablo,

You make a good point about location; it should be left as is.
As for rotation, your code has a rotation attribute, but I could not 
figure out how to use it:

///rotation = bpy.props.FloatVectorProperty(
         name="Rotation",
         subtype='EULER',
         )/

But there is a problem with my idea of having the normals face downward. 
If the meshlight is set as the camera (which I sometimes use to aim the 
light), it is backwards, facing away from the scene. So my idea may be 
totally off and your code may be perfect as is.

Mark

-------- Original Message --------
*Subject: *Re: [amaranth] Update meshlight_add.py (#7)
*From: *Pablo Vazquez <notifications@github.com>
*To: *venomgfx/amaranth <amaranth@noreply.github.com>
*Cc: *Mark <riveter@gmail.com>
*Date: *2/14/2015 3:06 PM

**Comment by riveter1** [comment]
Pablo,

Since a Camera looks in its (- Z) direction, in order for the meshlight 
to work as a Camera, I need to enter edit mode and rotate it 180°, then 
back to object mode. Now the normals will face the scene and it can be 
used as a Camera.

Mark
-------- Original Message --------
*Subject: *Re: [amaranth] Update meshlight_add.py (#7)
*From: *Pablo Vazquez <notifications@github.com>
*To: *venomgfx/amaranth <amaranth@noreply.github.com>
*Cc: *Mark <riveter@gmail.com>
*Date: *2/14/2015 3:06 PM

**Comment by riveter1** [comment]
Pablo,

My fix to the meshlight code is here:

https://github.com/riveter1/amaranth/blob/master/render/meshlight_add.py

Mark
-------- Original Message --------
*Subject: *Re: [amaranth] Update meshlight_add.py (#7)
*From: *Pablo Vazquez <notifications@github.com>
*To: *venomgfx/amaranth <amaranth@noreply.github.com>
*Cc: *Mark <riveter@gmail.com>
*Date: *2/14/2015 3:06 PM

**Comment by venomgfx** [comment]
Hi! 

Going over pull-requests from a couple years ago. Is this still relevant? If so I'll just merge the pull request.

**Comment by venomgfx** [comment]
I will close this for the moment, mainly since the version in Blender's official [add-ons contrib](https://developer.blender.org/diffusion/BAC/repository/master/) repository is more recent than the one used here. Please create pull requests there.

**Pull request closed without merging**
